# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from qai_hub_models_cli.proto import info_pb2
import shared.runtime_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ModelManifestUrls(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFO_FIELD_NUMBER: builtins.int
    PERF_FIELD_NUMBER: builtins.int
    NUMERICS_FIELD_NUMBER: builtins.int
    RELEASE_ASSETS_FIELD_NUMBER: builtins.int
    info: builtins.str
    perf: builtins.str
    numerics: builtins.str
    release_assets: builtins.str
    def __init__(
        self,
        *,
        info: builtins.str = ...,
        perf: builtins.str = ...,
        numerics: builtins.str = ...,
        release_assets: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["info", b"info", "numerics", b"numerics", "perf", b"perf", "release_assets", b"release_assets"]) -> None: ...

global___ModelManifestUrls = ModelManifestUrls

@typing.final
class ManifestModelEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    MANIFEST_URLS_FIELD_NUMBER: builtins.int
    IS_QUANTIZED_FIELD_NUMBER: builtins.int
    SUPPORTED_RUNTIMES_FIELD_NUMBER: builtins.int
    SUPPORTED_CHIPSETS_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    id: builtins.str
    display_name: builtins.str
    domain: info_pb2.ModelDomain.ValueType
    is_quantized: builtins.bool
    """Fields 5-8 (the model-filter fields) were added in AI Hub Models 0.56.0.
    They are unset/empty in manifests from earlier releases, so consumers must
    only rely on them when the manifest version is >= 0.56.0.

    Whether the model has any quantized (non-float) released assets.
    """
    @property
    def manifest_urls(self) -> global___ModelManifestUrls: ...
    @property
    def supported_runtimes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[shared.runtime_pb2.Runtime.ValueType]:
        """Runtimes for which the model has released assets."""

    @property
    def supported_chipsets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Chipsets on which the model has been profiled."""

    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[info_pb2.ModelTag.ValueType]:
        """Tags applied to the model (mirrors ModelInfo.tags)."""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        display_name: builtins.str = ...,
        domain: info_pb2.ModelDomain.ValueType = ...,
        manifest_urls: global___ModelManifestUrls | None = ...,
        is_quantized: builtins.bool = ...,
        supported_runtimes: collections.abc.Iterable[shared.runtime_pb2.Runtime.ValueType] | None = ...,
        supported_chipsets: collections.abc.Iterable[builtins.str] | None = ...,
        tags: collections.abc.Iterable[info_pb2.ModelTag.ValueType] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["manifest_urls", b"manifest_urls"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["display_name", b"display_name", "domain", b"domain", "id", b"id", "is_quantized", b"is_quantized", "manifest_urls", b"manifest_urls", "supported_chipsets", b"supported_chipsets", "supported_runtimes", b"supported_runtimes", "tags", b"tags"]) -> None: ...

global___ManifestModelEntry = ManifestModelEntry

@typing.final
class ReleaseManifest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    PLATFORM_URL_FIELD_NUMBER: builtins.int
    MODELS_FIELD_NUMBER: builtins.int
    version: builtins.str
    platform_url: builtins.str
    @property
    def models(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ManifestModelEntry]: ...
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        platform_url: builtins.str = ...,
        models: collections.abc.Iterable[global___ManifestModelEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["models", b"models", "platform_url", b"platform_url", "version", b"version"]) -> None: ...

global___ReleaseManifest = ReleaseManifest
